name: sfpark
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - lightgbm=3.1.1
  - matplotlib=3.3.4
  - numpy-base=1.20.2
  - pandas=1.2.5
  - pip=21.1.2
  - py-xgboost=1.3.3
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7.6.5_0
  - scikit-learn=0.24.2
  - tensorboard=2.5.0
  - tqdm=4.62.0
  - xgboost=1.3.3
  - pip:
    - networkx
    - numpy==1.21.0
    - scipy==1.7.0
    - torch==1.6.0
    - torch-geometric==2.0.3
    - torch-geometric-temporal==0.50.0
    - torch-scatter==2.0.9
    - torch-sparse==0.6.12
    - torchdiffeq==0.2.2
    - torchdiffeqpack==0.1.0